//
//  constants.swift
//  BookManager
//

import Foundation
import SwiftUI

public let SETTING_THEME_KEY = "SETTING_THEME_KEY"

public let SETTING_GRID_COLUMNS_KEY = "SETTING_GRID_COLUMNS_KEY"

public let SETTING_ACCENT_COLOR_KEY = "SETTING_ACCENT_COLOR_KEY"

public let SETTING_ACCENT_COLOR_DEFAULT_VALUE = Color.blue
//"SETTING_SHOW_COMPLETED_BOOKS_KEY"

public let SETTING_GRID_COLUMNS_DEFAULT_VALUE: Int = 2
